24 - May - 2020 - Sunday :
--------------------------
ERROR: Command errored out with exit status 1:
     command: /Users/sai/anaconda3/envs/py37/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/0n/2zpnf3mn1fg1dghpb2007c6w0000gn/T/pip-install-ykxrdgs6/mysqlclient/setup.py'"'"'; __file__='"'"'/private/var/folders/0n/2zpnf3mn1fg1dghpb2007c6w0000gn/T/pip-install-ykxrdgs6/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/0n/2zpnf3mn1fg1dghpb2007c6w0000gn/T/pip-install-ykxrdgs6/mysqlclient/pip-egg-info
         cwd: /private/var/folders/0n/2zpnf3mn1fg1dghpb2007c6w0000gn/T/pip-install-ykxrdgs6/mysqlclient/
    Complete output (12 lines):
    /bin/sh: mysql_config: command not found
    /bin/sh: mariadb_config: command not found
    /bin/sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/0n/2zpnf3mn1fg1dghpb2007c6w0000gn/T/pip-install-ykxrdgs6/mysqlclient/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/private/var/folders/0n/2zpnf3mn1fg1dghpb2007c6w0000gn/T/pip-install-ykxrdgs6/mysqlclient/setup_posix.py", line 61, in get_config
        libs = mysql_config("libs")
      File "/private/var/folders/0n/2zpnf3mn1fg1dghpb2007c6w0000gn/T/pip-install-ykxrdgs6/mysqlclient/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

--------------------------------------------------------------------------------------------------------------

2) (py37) Sais-MacBook-Pro:mysql python sample sai$ pip install mysqlclient==1.4.2.post1
Collecting mysqlclient==1.4.2.post1
  Downloading mysqlclient-1.4.2.post1.tar.gz (85 kB)
     |████████████████████████████████| 85 kB 2.0 MB/s
    ERROR: Command errored out with exit status 1:
     command: /Users/sai/anaconda3/envs/py37/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/0n/2zpnf3mn1fg1dghpb2007c6w0000gn/T/pip-install-o01419zn/mysqlclient/setup.py'"'"'; __file__='"'"'/private/var/folders/0n/2zpnf3mn1fg1dghpb2007c6w0000gn/T/pip-install-o01419zn/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/0n/2zpnf3mn1fg1dghpb2007c6w0000gn/T/pip-install-o01419zn/mysqlclient/pip-egg-info
         cwd: /private/var/folders/0n/2zpnf3mn1fg1dghpb2007c6w0000gn/T/pip-install-o01419zn/mysqlclient/
    Complete output (10 lines):
    /bin/sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/0n/2zpnf3mn1fg1dghpb2007c6w0000gn/T/pip-install-o01419zn/mysqlclient/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/private/var/folders/0n/2zpnf3mn1fg1dghpb2007c6w0000gn/T/pip-install-o01419zn/mysqlclient/setup_posix.py", line 51, in get_config
        libs = mysql_config("libs")
      File "/private/var/folders/0n/2zpnf3mn1fg1dghpb2007c6w0000gn/T/pip-install-o01419zn/mysqlclient/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
=============================================================================================================================================================================

Traceback (most recent call last):
  File "test.py", line 7, in <module>
    db="tactdb")
  File "/Users/sai/anaconda3/envs/py37/lib/python3.7/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/Users/sai/anaconda3/envs/py37/lib/python3.7/site-packages/MySQLdb/connections.py", line 179, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2002, "Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)")

=====================================================================